### ISSUE TITLE
Ben's Lab

### ISSUE THREAD

**Issue by pretorben** [ga-wdi-exercises/redux-reminderly#17]
https://github.com/pretorben/redux_shopping_cart/tree/master/shopping-cart

Completeness: 5
Comfort Level: 2

Redux is brutal.  I sort of understand what's going on, but not enough to build any apps with it.

**Comment by superbuggy** [comment]
👍 Yeah Redux is brutal. If you want some recommendations for resources to go deeper with Redux, let me know.
