### ISSUE TITLE
Nyketha's Lab

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/redux-reminderly#18]
link to repo: https://github.com/Nykke/Redux-Reminderly-Lab

comments: I kept getting an undefined for .map in the containers file, not sure why.

confidence: 2
completeness: 5

**Comment by superbuggy** [comment]
```js
class App extends Component {
  render(){
    return(
      <List /> 
    )
  }
}
```

have to pass in a list as a prop there

👍
