### ISSUE TITLE
Shopping Cart - Will Hawkins

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/redux-reminderly#3]
REPO: https://github.com/hawkins-will/react-redux-shopping-cart

Complete: 5/5

Comfort: 2/5 at best?

I followed the instructions, but to be honest, my brain has pretty much given out today and I think I might have fallen asleep and kept typing somehow. So really I'm not sure what exactly I did :-/

**Comment by nayana487** [comment]
👍
